/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.RepoVentasDTO;
import excepciones.PersistenciaException;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import reporteBO.RepoVentasBO;

/**
 *
 * @author OMEN
 */
public class JReportes extends javax.swing.JFrame {

    /**
     * Creates new form JReportes
     */
    public JReportes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnRepoVentas = new javax.swing.JButton();
        btnRepoCompras = new javax.swing.JButton();
        btnRepoInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(144, 180, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBackground(new java.awt.Color(247, 94, 94));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 150, 70));

        btnRepoVentas.setBackground(new java.awt.Color(174, 228, 68));
        btnRepoVentas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRepoVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnRepoVentas.setText("Generar");
        btnRepoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepoVentasActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 150, 70));

        btnRepoCompras.setBackground(new java.awt.Color(174, 228, 68));
        btnRepoCompras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRepoCompras.setForeground(new java.awt.Color(0, 0, 0));
        btnRepoCompras.setText("Generar");
        jPanel2.add(btnRepoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 150, 70));

        btnRepoInventario.setBackground(new java.awt.Color(174, 228, 68));
        btnRepoInventario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRepoInventario.setForeground(new java.awt.Color(0, 0, 0));
        btnRepoInventario.setText("Generar");
        jPanel2.add(btnRepoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 150, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\OMEN\\Documents\\GitHub\\proye_Sw_Integrador\\Presentacion3Hermanos\\src\\main\\resource\\FondoReportes.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1250, 700));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRepoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepoVentasActionPerformed
        RepoVentasBO bo = new RepoVentasBO();
        try {
            List<RepoVentasDTO> reporte = bo.obtenerReporteDelDia();

            // Ruta y nombre del archivo
            String rutaArchivo = "reporte_ventas.txt";

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(rutaArchivo))) {
                writer.write("=== REPORTE DE VENTAS ===\n");
                writer.write("Fecha de generación: " + java.time.LocalDate.now() + "\n\n");

                for (RepoVentasDTO dto : reporte) {
                    writer.write("Producto: " + dto.getNombreProducto() + "\n");
                    writer.write("Cantidad Vendida: " + dto.getCantidadVendida() + "\n");
                    writer.write("Total Ganado: $" + dto.getTotalGanancias() + "\n");
                    writer.write("------------------------------------\n");
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Reporte generado con éxito en:\n" + rutaArchivo);
            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al escribir el archivo: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Imprimir error de escritura
            }

        } catch (PersistenciaException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al obtener reporte: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Esto imprimirá el error completo en la consola
        }
    }//GEN-LAST:event_btnRepoVentasActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        JVenta jVenta = new JVenta();
        jVenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRepoCompras;
    private javax.swing.JButton btnRepoInventario;
    private javax.swing.JButton btnRepoVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
