/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import org.eclipse.persistence.jpa.JpaEntityManager;
import net.sf.dynamicreports.report.builder.column.TextColumnBuilder;
import static net.sf.dynamicreports.report.builder.DynamicReports.*;
import org.eclipse.persistence.sessions.server.ServerSession;
import org.eclipse.persistence.sessions.UnitOfWork;
import org.eclipse.persistence.internal.databaseaccess.Accessor;
import java.sql.Connection;
import conexionEM.Conexion;
import dtos.RepoVentasDTO;
import excepciones.PersistenciaException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static net.sf.dynamicreports.report.builder.DynamicReports.col;
import reportes.Templates;
import static net.sf.dynamicreports.report.builder.DynamicReports.report;
import net.sf.dynamicreports.report.builder.VariableBuilder;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.column.TextColumnBuilder;
import net.sf.dynamicreports.report.builder.component.Components;
import net.sf.dynamicreports.report.builder.datatype.DataTypes;
import net.sf.dynamicreports.report.constant.Calculation;
import net.sf.dynamicreports.report.constant.HorizontalTextAlignment;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.eclipse.persistence.sessions.Session;
import org.eclipse.persistence.sessions.UnitOfWork;
import reporteBO.RepoVentasBO;
import reportes.CustomExpression;

/**
 *
 * @author OMEN
 */
public class JReportes extends javax.swing.JFrame {

    /**
     * Creates new form JReportes
     */
    public JReportes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnRepoVentas = new javax.swing.JButton();
        btnRepoCompras = new javax.swing.JButton();
        btnRepoInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(144, 180, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBackground(new java.awt.Color(247, 94, 94));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 150, 70));

        btnRepoVentas.setBackground(new java.awt.Color(174, 228, 68));
        btnRepoVentas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRepoVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnRepoVentas.setText("Generar");
        btnRepoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepoVentasActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 150, 70));

        btnRepoCompras.setBackground(new java.awt.Color(174, 228, 68));
        btnRepoCompras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRepoCompras.setForeground(new java.awt.Color(0, 0, 0));
        btnRepoCompras.setText("Generar");
        jPanel2.add(btnRepoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 150, 70));

        btnRepoInventario.setBackground(new java.awt.Color(174, 228, 68));
        btnRepoInventario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRepoInventario.setForeground(new java.awt.Color(0, 0, 0));
        btnRepoInventario.setText("Generar");
        jPanel2.add(btnRepoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 150, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\OMEN\\Documents\\GitHub\\proye_Sw_Integrador\\Presentacion3Hermanos\\src\\main\\resource\\FondoReportes.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1250, 700));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRepoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepoVentasActionPerformed
//        RepoVentasBO bo = new RepoVentasBO();
//        try {
//            List<RepoVentasDTO> reporte = bo.obtenerReporteDelDia();
//
//            // Ruta y nombre del archivo
//            String rutaArchivo = "reporte_ventas.txt";
//
//            try (BufferedWriter writer = new BufferedWriter(new FileWriter(rutaArchivo))) {
//                writer.write("=== REPORTE DE VENTAS ===\n");
//                writer.write("Fecha de generación: " + java.time.LocalDate.now() + "\n\n");
//
//                for (RepoVentasDTO dto : reporte) {
//                    writer.write("Producto: " + dto.getNombreProducto() + "\n");
//                    writer.write("Cantidad Vendida: " + dto.getCantidadVendida() + "\n");
//                    writer.write("Total Ganado: $" + dto.getTotalGanancias() + "\n");
//                    writer.write("------------------------------------\n");
//                }
//
//                javax.swing.JOptionPane.showMessageDialog(this, "Reporte generado con éxito en:\n" + rutaArchivo);
//            } catch (IOException e) {
//                javax.swing.JOptionPane.showMessageDialog(this, "Error al escribir el archivo: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
//                e.printStackTrace(); // Imprimir error de escritura
//            }
//
//        } catch (PersistenciaException e) {
//            javax.swing.JOptionPane.showMessageDialog(this, "Error al obtener reporte: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
//            e.printStackTrace(); // Esto imprimirá el error completo en la consola
//        }

        try {
            Conexion conexion = new Conexion();
            EntityManager em = conexion.abrir();

            // Usar unwrap para obtener Connection a partir de EntityManager
            JpaEntityManager jpaEm = em.unwrap(JpaEntityManager.class);
            org.eclipse.persistence.sessions.Session session = jpaEm.getActiveSession();
            Connection conn = (Connection) ((org.eclipse.persistence.internal.sessions.UnitOfWorkImpl) session).getAccessor().getConnection();

            String sql = """
            SELECT 
                p.nombre AS producto,
                SUM(pt.cantidad) AS cantidad,
                pt.precio,
                SUM(pt.cantidad * pt.precio) AS total_producto
            FROM 
                productotransacciones pt
            JOIN 
                productos p ON pt.producto_id = p.ID
            JOIN 
                transacciones t ON pt.transaccion_id = t.ID
            JOIN 
                venta v ON t.ID = v.ID
            WHERE 
                DATE(pt.fecha_hora) = CURRENT_DATE
            GROUP BY 
                p.nombre, pt.precio
        """;

            JRDataSource dataSource = new JRResultSetDataSource(conn.createStatement().executeQuery(sql));

            TextColumnBuilder<String> colProducto = col.column("Producto", "producto", type.stringType());
            TextColumnBuilder<Integer> colCantidad = col.column("Cantidad", "cantidad", type.integerType());
            TextColumnBuilder<Double> colPrecio = col.column("Precio Unitario", "precio", type.doubleType());
            TextColumnBuilder<Double> colTotal = col.column("Total", "total_producto", type.doubleType());

            VariableBuilder<Integer> varCantidadSum = variable(colCantidad, Calculation.SUM);
            VariableBuilder<Double> varTotalSum = variable(colTotal, Calculation.SUM);

            JasperPrint jasperPrint = report()
                    .title(
                            Components.text("ABARROTES 3 HERMANOS").setStyle(Templates.bold18CenteredStyle),
                            Components.text("Reporte de ventas").setStyle(Templates.bold12CenteredStyle),
                            Components.text("Fecha: " + java.time.LocalDate.now()).setStyle(Templates.rootStyle)
                    )
                    .setColumnTitleStyle(Templates.bold12CenteredStyle)
                    
                    .columns(
                            Columns.column("Producto", "producto", DataTypes.stringType())
                                    .setStyle(Templates.rootStyle).setHorizontalTextAlignment(HorizontalTextAlignment.CENTER),
                            Columns.column("Cantidad", "cantidad", DataTypes.integerType())
                                    .setStyle(Templates.rootStyle).setHorizontalTextAlignment(HorizontalTextAlignment.CENTER),
                            Columns.column("Precio Unitario", "precio", DataTypes.doubleType())
                                    .setStyle(Templates.rootStyle).setHorizontalTextAlignment(HorizontalTextAlignment.CENTER),
                            Columns.column("Total", "total_producto", DataTypes.doubleType())
                                    .setStyle(Templates.rootStyle).setHorizontalTextAlignment(HorizontalTextAlignment.CENTER)
                    )
                    .summary(
                            
                            Components.line(),
                            Components.text("Resumen del día")
                                    .setStyle(Templates.bold12CenteredStyle)
                                    .setHorizontalTextAlignment(HorizontalTextAlignment.RIGHT),
                            // Primera fila: total de productos
                            Components.horizontalList(
                                    Components.text("Total de Productos:")
                                            .setStyle(Templates.rootStyle)
                                            .setHorizontalTextAlignment(HorizontalTextAlignment.LEFT)
                                            .setFixedWidth(400),
                                    Components.text(varCantidadSum)
                                            .setStyle(Templates.rootStyle)
                                            .setHorizontalTextAlignment(HorizontalTextAlignment.RIGHT)
                                            .setPattern("#,##0")
                            ).newRow(),
                            // Segunda fila: total ganado
                            Components.horizontalList(
                                    Components.text("Total Ganado: $")
                                            .setStyle(Templates.rootStyle)
                                            .setHorizontalTextAlignment(HorizontalTextAlignment.LEFT)
                                            .setFixedWidth(400),
                                    Components.text(varTotalSum)
                                            .setStyle(Templates.rootStyle)
                                            .setHorizontalTextAlignment(HorizontalTextAlignment.RIGHT)
                                            .setPattern("#,##0.00")
                            ),
                            Components.line()
                    )
                    .pageFooter(Components.pageXofY())
                    .setDataSource(dataSource)
                    .toJasperPrint();

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            viewer.addWindowListener(new WindowAdapter() {
            });
            viewer.setVisible(true);

            em.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + e.getMessage());
        }


    }//GEN-LAST:event_btnRepoVentasActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        JVenta jVenta = new JVenta();
        jVenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRepoCompras;
    private javax.swing.JButton btnRepoInventario;
    private javax.swing.JButton btnRepoVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
